[template.environment]
  GQL_HOST = "https://cnelement.com/graphql"
#  GQL_HOST = "WordPress URL http://example.com"
  NUXT_IMAGE_DOMAINS = "Comma separated list of domains. example.com,example2.com"
GRAPHQL_DEBUG=true
[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.woonuxt.com/.*"]
